/**
 * AeroLink – Baggage Tracking Service
 * Port: 3002
 * Also hosts /api/notifications (generated by baggage status updates)
 */
const express = require('express');
const { DynamoDBClient } = require('@aws-sdk/client-dynamodb');
const { DynamoDBDocumentClient, PutCommand, ScanCommand, GetCommand, UpdateCommand } = require('@aws-sdk/lib-dynamodb');

const app  = express();
const PORT = 3002;
app.use(express.json());

const USE_DYNAMODB = process.env.NODE_ENV === 'production' || process.env.USE_DYNAMODB === 'true';
const dbClient = new DynamoDBClient({ region: process.env.AWS_REGION || 'us-east-1' });
const docClient = DynamoDBDocumentClient.from(dbClient);
const TABLE_NAME = process.env.DYNAMODB_BAGGAGE_TABLE || 'AeroLink-Baggage';

// ── Stores ───────────────────────────────────────────────────────────────────
let nextBagId = 5;
let baggageStore = {
    1: { id: 1, bookingId: null,  tagNumber: 'BAG-77102', passengerName: 'Risindu',      flightId: 'AL-101', status: 'In Transit',            location: 'Colombo (CMB)', lastUpdated: new Date().toISOString() },
    2: { id: 2, bookingId: null,  tagNumber: 'BAG-83241', passengerName: 'James Smith',  flightId: 'AL-202', status: 'Loaded on Aircraft',     location: 'London (LHR)',  lastUpdated: new Date().toISOString() },
    3: { id: 3, bookingId: null,  tagNumber: 'BAG-56789', passengerName: 'Sara Ahmed',   flightId: 'AL-303', status: 'In Transit',             location: 'Dubai (DXB)',   lastUpdated: new Date().toISOString() },
    4: { id: 4, bookingId: null,  tagNumber: 'BAG-11022', passengerName: 'Chen Wei',     flightId: 'AL-404', status: 'Arrived at Destination', location: 'Dubai (DXB)',   lastUpdated: new Date().toISOString() },
};

const VALID_STATUSES = [
    'Checked In', 'Sorting Facility', 'Loaded on Aircraft',
    'In Transit', 'Arrived at Destination', 'Available for Collection',
    'Collected', 'Delayed', 'Lost',
    // Keep old-format statuses for backward compat
    'CHECK_IN_RECEIVED', 'SORTING_FACILITY', 'LOADED_ON_AIRCRAFT',
    'IN_TRANSIT', 'ARRIVED', 'AVAILABLE_FOR_COLLECTION', 'COLLECTED', 'LOST',
];

// ── Notifications store ───────────────────────────────────────────────────────
let nextNotifId = 1;
const notifications = [];

function addNotification(type, bookingId, message) {
    notifications.unshift({
        id:        nextNotifId++,
        type,
        bookingId: bookingId || null,
        message,
        createdAt: new Date().toISOString()
    });
    if (notifications.length > 100) notifications.pop();
}

// ── Health ───────────────────────────────────────────────────────────────────
app.get('/api/health', (req, res) => res.json({ service: 'baggage-service', status: 'healthy', records: Object.keys(baggageStore).length, timestamp: new Date().toISOString() }));

// ── GET /api/baggage ──────────────────────────────────────────────────────────
app.get('/api/baggage', async (req, res) => {
    if (USE_DYNAMODB) {
        try {
            const result = await docClient.send(new ScanCommand({ TableName: TABLE_NAME }));
            res.json(result.Items ? result.Items.reverse() : []);
        } catch(e) {
            res.status(500).json({ error: e.message });
        }
    } else {
        res.json(Object.values(baggageStore).reverse());
    }
});

// ── GET /api/baggage/all ──────────────────────────────────────────────────────
app.get('/api/baggage/all', async (req, res) => {
    if (USE_DYNAMODB) {
        try {
            const result = await docClient.send(new ScanCommand({ TableName: TABLE_NAME }));
            res.json({ source: 'DynamoDB', count: (result.Items||[]).length, data: result.Items ? result.Items.reverse() : [] });
        } catch(e) {
            res.status(500).json({ error: e.message });
        }
    } else {
        const data = Object.values(baggageStore).reverse();
        res.json({ source: 'Local Memory', count: data.length, data });
    }
});

// ── GET /api/baggage/track/:id ─────────────────────────────────────────────
app.get('/api/baggage/track/:id', async (req, res) => {
    if (USE_DYNAMODB) {
        try {
            const result = await docClient.send(new GetCommand({ TableName: TABLE_NAME, Key: { tagNumber: req.params.id } }));
            if (!result.Item) return res.status(404).json({ error: `Baggage ${req.params.id} not found` });
            res.json({ source: 'DynamoDB', data: result.Item });
        } catch (e) {
            res.status(500).json({ error: e.message });
        }
    } else {
        const record = Object.values(baggageStore).find(b => b.tagNumber === req.params.id || String(b.id) === req.params.id);
        if (!record) return res.status(404).json({ error: `Baggage ${req.params.id} not found` });
        res.json({ source: 'Local Memory', data: record });
    }
});

// ── POST /api/baggage – Create new baggage record ─────────────────────────────
app.post('/api/baggage', async (req, res) => {
    const { bookingId, passengerName, tagNumber, flightId } = req.body;
    if (!passengerName) return res.status(400).json({ error: 'passengerName is required' });
    const id  = nextBagId++;
    const tag = tagNumber || ('BAG-' + Math.floor(Math.random() * 90000 + 10000));
    
    const record = {
        id, bookingId: bookingId || null, tagNumber: tag,
        passengerName, flightId: flightId || null,
        status: 'Checked In', location: 'Check-in desk',
        lastUpdated: new Date().toISOString()
    };

    if (USE_DYNAMODB) {
        await docClient.send(new PutCommand({ TableName: TABLE_NAME, Item: record }));
    } else {
        baggageStore[id] = record;
    }

    addNotification('BAGGAGE_CREATED', bookingId, `Baggage ${tag} created for ${passengerName}`);
    console.log(JSON.stringify({ level: 'INFO', event: 'BAGGAGE_CREATED', tagNumber: tag, passengerName }));
    res.status(201).json({ message: 'Baggage record created', baggage: record });
});

// ── PUT /api/baggage/:id/status – Update status ───────────────────────────────
app.put('/api/baggage/:id/status', async (req, res) => {
    const { status, location } = req.body;
    if (!status) return res.status(400).json({ error: 'status is required' });

    let record;
    if (USE_DYNAMODB) {
        const getRes = await docClient.send(new GetCommand({ TableName: TABLE_NAME, Key: { tagNumber: req.params.id } }));
        if (!getRes.Item) return res.status(404).json({ error: `Baggage ${req.params.id} not found` });
        record = getRes.Item;
        record.status = status;
        record.location = location || record.location;
        record.lastUpdated = new Date().toISOString();
        await docClient.send(new PutCommand({ TableName: TABLE_NAME, Item: record }));
    } else {
        record = baggageStore[req.params.id] || Object.values(baggageStore).find(b => b.tagNumber === req.params.id);
        if (!record) return res.status(404).json({ error: `Baggage ${req.params.id} not found` });
        record.status      = status;
        record.location    = location || record.location;
        record.lastUpdated = new Date().toISOString();
    }

    addNotification('BAGGAGE_STATUS_UPDATED', record.bookingId, `Baggage ${record.tagNumber} updated to: ${status}`);
    console.log(JSON.stringify({ level: 'INFO', event: 'BAGGAGE_STATUS_UPDATED', tagNumber: record.tagNumber, status }));
    res.json({ message: 'Status updated', data: record });
});

// ── POST /api/baggage/update – legacy endpoint ────────────────────────────────
app.post('/api/baggage/update', async (req, res) => {
    const { baggageId, status, location, passenger, flightId } = req.body;
    if (!baggageId || !status) return res.status(400).json({ error: 'baggageId and status are required' });
    if (!VALID_STATUSES.includes(status)) return res.status(400).json({ error: 'Invalid status' });
    
    let record;
    if (USE_DYNAMODB) {
        const getRes = await docClient.send(new GetCommand({ TableName: TABLE_NAME, Key: { tagNumber: baggageId } }));
        if (!getRes.Item) {
            const id = nextBagId++;
            record = { id, bookingId: null, tagNumber: baggageId, passengerName: passenger || 'Unknown', flightId: flightId || null, status, location: location || 'Unknown', lastUpdated: new Date().toISOString() };
            await docClient.send(new PutCommand({ TableName: TABLE_NAME, Item: record }));
            addNotification('BAGGAGE_STATUS_UPDATED', null, `Baggage ${baggageId} registered with status: ${status}`);
            return res.json({ message: 'Baggage registered', source: 'DynamoDB', data: record });
        }
        record = getRes.Item;
        record.status = status;
        record.location = location || record.location;
        record.lastUpdated = new Date().toISOString();
        await docClient.send(new PutCommand({ TableName: TABLE_NAME, Item: record }));
    } else {
        if (!baggageStore[baggageId] && !Object.values(baggageStore).find(b => b.tagNumber === baggageId)) {
            const id = nextBagId++;
            baggageStore[id] = { id, bookingId: null, tagNumber: baggageId, passengerName: passenger || 'Unknown', flightId: flightId || null, status, location: location || 'Unknown', lastUpdated: new Date().toISOString() };
            addNotification('BAGGAGE_STATUS_UPDATED', null, `Baggage ${baggageId} registered with status: ${status}`);
            return res.json({ message: 'Baggage registered', source: 'Local Memory', data: baggageStore[id] });
        }
        record = baggageStore[baggageId] || Object.values(baggageStore).find(b => b.tagNumber === baggageId);
        Object.assign(record, { status, location: location || record.location, lastUpdated: new Date().toISOString() });
    }

    addNotification('BAGGAGE_STATUS_UPDATED', record.bookingId, `Baggage ${record.tagNumber} status: ${status}`);
    res.json({ message: 'Baggage status synchronized', source: USE_DYNAMODB ? 'DynamoDB' : 'Local Memory', data: record });
});

// ── GET /api/notifications ────────────────────────────────────────────────────
app.get('/api/notifications', (req, res) => {
    res.json(notifications);
});

if (require.main === module) {
    app.listen(PORT, () =>
        console.log(JSON.stringify({ level: 'INFO', service: 'baggage-service', port: PORT, status: 'started' }))
    );
}
module.exports = app;